[general]

[dns]
server=1.1.1.1

[policy]
static=Final, direct

[server_remote]

[filter_remote]

[rewrite_remote]

[server_local]

[filter_local]
final, Final

[rewrite_local]
[rewrite_remote]
# YouTube: Chặn quảng cáo, phát nền, mở khóa Premium giả lập
https://fastly.jsdelivr.net/gh/Maasea/sgmodule@master/Rewrite/YouTube_Ads.conf, tag=YouTube Premium, update-interval=86400, opt-parser=true, enabled=true

# TikTok: Chặn quảng cáo, tải video không logo, mở khóa khu vực
https://fastly.jsdelivr.net/gh/Keyw0rth/Tiktok@main/Rewrite/Tiktok.conf, tag=TikTok Pro, update-interval=86400, opt-parser=true, enabled=true

# Facebook & Messenger: Chặn bài viết tài trợ, quảng cáo tin nhắn
https://fastly.jsdelivr.net/gh/Solyca/Rules@master/Facebook/facebook_ads.conf, tag=Facebook Ads, update-interval=86400, opt-parser=true, enabled=true

# Tachimanga
^https?:\/\/.*\.applovin\.com\/.* url reject
^https?:\/\/.*\.googlesyndication\.com\/.* url reject

[mitm]
hostname = *.googlevideo.com, youtubei.googleapis.com, www.youtube.com, *.tiktokv.com, *.byteoversea.com, graph.facebook.com, *.facebook.com, facebook.com, *.applovin.com, *.googlesyndication.com
