[general]

[dns]
server=1.1.1.1

[policy]
static=Final, direct

[server_remote]

[filter_remote]

[rewrite_remote]

[server_local]

[filter_local]
final, Final

[rewrite_local]
# YouTube
^https?:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|search|reel\/item_details|guide|get_watch_next) url script-response-body https://fastly.jsdelivr.net/gh/Maasea/sgmodule@master/Script/Youtube/youtube.js
^https?:\/\/[\w-]+\.googlevideo\.com\/videoplayback.*(&adformat=|&oad=) url reject

# TikTok
^https?:\/\/.*\.tiktokv\.com\/aweme\/v\d\/(feed|post|nearby) url script-response-body https://fastly.jsdelivr.net/gh/Keyw0rth/Tiktok@main/Scripts/tiktok.js
^https?:\/\/.*\.byteoversea\.com\/.* url reject

# Facebook & Tachimanga
^https?:\/\/graph\.facebook\.com\/v\d+\.\d+\/.*(sponsored_data|ads_data) url reject
^https?:\/\/.*\.facebook\.com\/api\/graphql\/ url script-response-body https://fastly.jsdelivr.net/gh/Solyca/Rules@master/Facebook/facebook_ads.js
^https?:\/\/.*\.applovin\.com\/.* url reject
^https?:\/\/.*\.googlesyndication\.com\/.* url reject

[mitm]
hostname = *.googlevideo.com, youtubei.googleapis.com, www.youtube.com, *.tiktokv.com, *.byteoversea.com, graph.facebook.com, *.facebook.com, facebook.com, *.applovin.com, *.googlesyndication.com
