# Crack Adguard Pro Premium

hostname = mobile-api.adguard.org

# Pro

^https?:\/\/mobile-api\.adguard\.org\/api\/.+\/ios_validate_receipt url script-response-body https://raw.githubusercontent.com/yqc007/QuantumultX/master/AdGuardProCrack.js
