#Bilibili.tv Adblock

# 1.MitM 

hostname = apiintl.biliapi.net, *.bstarstatic.com, apstar-v2.biliapi.net

# 2.Rewrite 

 # [Bilibili Intl] Chặn quảng cáo khởi động (Splash)
^https:\/\/apiintl\.biliapi\.net\/intl\/gateway\/v2\/app\/splash url reject-200

 # [Bilibili Intl] Chặn các gói tin quảng cáo trong luồng (Ads/Feed)
^https:\/\/apiintl\.biliapi\.net\/intl\/gateway\/v2\/app\/ad url reject-200

 # [Bilibili Intl] Chặn Tracking & Analytics
^https:\/\/apiintl\.biliapi\.net\/intl\/gateway\/v2\/app\/index\/icon url reject-200
^https:\/\/apstar-v2\.biliapi\.net\/intl\/gateway\/v2\/app\/search\/default\/word url reject-200

 # [Bilibili Intl] Chặn tài nguyên hình ảnh quảng cáo
^https:\/\/.+\.bstarstatic\.com\/.+\.(jpg|png)$ url reject-img

# 3.Filter
  
domain-suffix, bstarstatic.com, reject
domain, tracker.bilibili.tv, reject
