
hostname = *.capcut.com, *.bytedance.net, *.bytedance.com
  
^https:\/\/.*\.capcut\.com\/.*(vip|pro|subscription).* url script-response-body https://raw.githubusercontent.com/trongson019/capcut-pro-shadowrocket1/main/capcut_pro.js
