# Tên: CapCut Pro Unlock
# Mô tả: Mở khóa CapCut Pro bản quyền miễn phí bằng MITM
# Tác giả: Duxng9324
# Cập nhật: 13/05/2025

hostname = *.capcut.net, *.bytedance.net

# Mở khóa CapCut Pro
^https:\/\/.*\.capcut\.net\/.*(vip|pro|subscription).* url script-response-body https://raw.githubusercontent.com/trongson019/capcut-pro-shadowrocket1/main/capcut_pro.js
