# Tên: CapCut Pro Unlock
# Mô tả: Mở khóa CapCut Pro bản quyền miễn phí bằng MITM
# Tác giả: Duxng9324
# Cập nhật: 13/05/2025

hostname = api.revenuecat.com, capcut.net, *.capcut.net

# Mở khóa CapCut Pro
^https:\/\/api\.revenuecat\.com\/v1\/subscribers\/.* url script-response-body https://raw.githubusercontent.com/duxng9324/CapCutPro/main/capcut.js

# Xóa header gửi đến RevenueCat để tránh bị phát hiện
^https:\/\/api\.revenuecat\.com\/v1\/(receipts|subscribers) url script-request-header https://raw.githubusercontent.com/duxng9324/CapCutPro/main/deleteHeader.js,timeout=60
