# Crack Guzheng master 

hostname = ://gistap.com

# Vip

^https?:\/\/a2\.gistap\.com\/api\/guzhengunity\/index\.php url script-response-body https://raw.githubusercontent.com/tranhuyen-tech/QuantumultX/main/Scripts/GuzhengMaster.js
