#!name=Unlock GuzhengMaster
#!desc=GuzhengMaster
#!author=tranhuyenbn

hostname = *.gistap.com

# Vip

^https?:\/\/a2\.gistap\.com\/api\/guzhengunity\/index\.php url script-response-body https://raw.githubusercontent.com/tranhuyen-tech/QuantumultX/main/Scripts/GuzhengMasterVIP.js
