# Crack Guzheng master 

hostname = ://gistap.com

# Vip

http-response ^https?:\/\/a2\.gistap\.com\/api\/guzhengunity\/index\.php script-path=https://raw.githubusercontent.com/tranhuyen-tech/QuantumultX/main/Scripts/GuzhengMaster.js, requires-body=true, timeout=10, tag=Mở khóa Guzheng Master Server
