[general]
; Cấu hình hệ thống tối ưu cho tính năng chạy ngầm ổn định khi lái xe
dns_server = 1.1.1.1, 8.8.8.8
excluded_routes = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12
network_check_url = http://google.com

[dns]
; Định tuyến DNS hệ thống giúp truy cập ứng dụng mượt mà hơn
server = 1.1.1.1
server = 8.8.8.8

[filter_local]
# [Wyn App Ads Blocking - Filter]
host-keyword, ads.google, reject
host-keyword, admob, reject
host-suffix, doubleclick.net, reject
host-suffix, googleads.g.doubleclick.net, reject
host-suffix, ://googlesyndication.com, reject
host-suffix, ://unity3d.com, reject
host-suffix, ://pangle.com, reject
host-suffix, pangle.io, reject

# Giữ lại các kết nối mạng khác để ứng dụng tải dữ liệu bản đồ bình thường
final = direct

[rewrite_local]
# [Wyn App Ads Blocking - Rewrite]
^https?:\/\/googleads\.g\.doubleclick\.net\/mads\/gma url reject-200
^https?:\/\/pagead2\.googlesyndication\.com\/pagead\/gen_204 url reject-200
^https?:\/\/.*\.pangle\.com\/api\/ad\/url url reject-200

[mitm]
# [Wyn App Ads Blocking - MitM]
hostname = googleads.g.doubleclick.net, ://googlesyndication.com, *.pangle.com
