#!name=Pro35 Ads Block
#!desc=Lightweight Ads Block (YouTube TikTok Facebook TachiManga)
#!system=ios

[rewrite_local]

# YouTube
^https?:\/\/(www|m)\.youtube\.com\/api\/stats\/ads url reject
^https?:\/\/(www|m)\.youtube\.com\/pagead\/ url reject
^https?:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/player\/ad_break url reject
^https?:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/ad url reject
^https?:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/log_event url reject
^https?:\/\/.*youtubei\.googleapis\.com\/.*tracking url reject
^https?:\/\/.*googlevideo\.com\/ptracking url reject

# TikTok
^https?:\/\/ads.*\.tiktok\.com url reject
^https?:\/\/analytics.*\.tiktok\.com url reject
^https?:\/\/log.*\.tiktokv\.com url reject
^https?:\/\/mon\.tiktokv\.com url reject
^https?:\/\/.*\.tiktokv\.com\/.*ad.* url reject
^https?:\/\/business-api\.tiktok\.com url reject

# Facebook
^https?:\/\/ads\.facebook\.com url reject
^https?:\/\/graph\.facebook\.com\/.*ad.* url reject
^https?:\/\/graph\.facebook\.com\/v.*\/ads url reject
^https?:\/\/connect\.facebook\.net\/.* url reject
^https?:\/\/analytics\.facebook\.com url reject

# TachiManga
^https?:\/\/.*tachimanga.*\/ads.* url reject
^https?:\/\/.*tachimanga.*\/advert.* url reject

[MITM]

hostname = youtube.com,*.youtube.com,*.googlevideo.com,*.youtubei.googleapis.com,*.tiktok.com,*.tiktokv.com,*.facebook.com
